### ISSUE TITLE
Header not found error.

### ISSUE THREAD

**Issue by nasabots** [TilCreator/Tapas-Comic-Downloader#23] opened 2020-07-30 16:05 UTC
Hi! I hope you're doing well. I just tried using this as it seems really helpful but I'm unable to download the comic I want.
I tried using the link of the series like you said in my case which is: [https://tapas.io/series/GhostBlade/](url)
But i always get this error.

`Loading GhostBlade...                                                                                                   Crawling 1/1...                                                                                                          [GhostBlade] (0 pages):                                                                                                
Checking folder...                                                                                                      Creating folder...                                                                                                      Downloading header...                                                                                                   Header not found                                                                                                        
Traceback (most recent call last):
  File "tapas-dl.py", line 152, in <module>
    if len(pq(f'https://tapas.io/episode/{data[0]["id"]}', headers={'user-agent': 'tapas-dl'})('.ep-epub-contents')) > 0:
IndexError: list index out of range`

**Comment by hamperfait** [comment] 2020-08-04 10:40
I'm having the same issue here...
I looked a bit into it, and apparently the problem is that pyquery isn't really doing the queries correctly, whenever there's a function call to `pq` it returns an empty list `[]`.
Hence when it tries to access a specific position in the list, it causes an exception and breaks.
I haven't found a single call to `pq` that queries the HTML correctly, it only returns `\n`

**Comment by haupass** [comment] 2020-08-08 15:19
Same problem here, wondering if anyone could fix this?

**Comment by TilCreator** [comment] 2020-08-22 13:00
I will have a look at it tomorrow (Wish I had someone else helping (opening issues is also helping, but still more work for me ^^))

**Comment by nasabots** [comment] 2020-08-22 14:12
Aww it's alright. Take your time and I know it can be tough working alone.
But we really appreciate your work and if it gets fixed it'll be like a
dream come true ❤️ thank you! And take it easy!
Good luck

**Comment by TilCreator** [comment] 2020-08-23 14:33
Fixed in fba0ab1
Let's hope it stays like this for a while ^^

**Closed as completed by TilCreator** 2020-08-23 14:33 UTC
